### PR TITLE
Fixed Elixir > 1.2 compile issues

### LINKED ISSUE #2: Compile error
I'm getting a compile error with this environment:

Elixir: 1.3.1
Erlang: 18
eastar: 0.4.0

This is the console output of the error:

```
== Compilation error on file lib/heapmap.ex ==
** (UndefinedFunctionError) function :with.__struct__/1 is undefined (module :with is not available)
    :with.__struct__({:with, [], [{:<-, [], [{:when, [], [{{:_, [], Kernel}, {:doc, [counter: -576460752303423179], Kernel}}, false]}, {{:., [], [{:__aliases__, [alias: false, counter: -576460752303423179], [:Module]}, :get_attribute]}, [], [{:__MODULE__, [counter: -576460752303423179], Kernel}, :h, [{:{}, [], [Astar.HeapMap, :__MODULE__, 0, [file: "lib/heapmap.ex", line: 9]]}]]}]}, [do: {:doc, [counter: -576460752303423179], Kernel}]]})
    (elixir) Kernel.Typespec.typespec/3
    (elixir) lib/kernel/typespec.ex:390: Kernel.Typespec.translate_type/3
    lib/heapmap.ex:1: (file)
```

### PR DESCRIPTION
**Pull request by narrowtux**
Updated libraries to non-broken versions:

 - triq to github.com/triqng/triq
 - excheck to 0.5.1

Removed elixir 1.2 requirement

This fixes #2

### CODE REVIEW

**Comment by narrowtux** [comment]
I tested this with elixir 1.4, should also work with 1.3. 

Next, warnings such as 

```
warning: the variable "options" is unsafe as it has been set inside a case/cond/receive/if/&&/||. Please explicitly return the variable value instead. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end
```

have to be fixed because allowing to change variables in a subscope will be dropped in later elixir versions.

**Comment by narrowtux** [comment]
triq has been updated because it fails to compile with erlang 19.

**Comment by wkhere** [comment]
CI fails because I also need to make it up to date with newer Elixirs/OTPs. I will probably switch back to Travis for this.

So please wait several days until this gets to Hex.

Thanks for the patch! :]]

**Comment by wkhere** [comment]
FYI, I updated some stuff to work more nicely with Elixir 1.4, plus switched back to Travis so the various versions get tested.

This is hexified as 0.4.2.

**Comment by narrowtux** [comment]
Thanks :)
